
---
title: "Processing seurat object"
author: "Ivo Borkus"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
    toc_float: yes
    number_sections: yes
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = T, message = FALSE, warning = FALSE,
    fig.align = "center", fig.width = 10, fig.height = 10
)
knitr::render_markdown()
```

```{css, echo = F}
pre code, pre, code {
  white-space: pre !important;
  overflow-x: scroll !important;
  word-break: keep-all !important;
  word-wrap: initial !important;
}

pre {
  max-height: 300px;
  overflow-y: auto;
}
```


```{r loading libraries, include = FALSE}
library(Seurat)
library(dplyr)
library(ggplot2)
library(here)
library(tidyr)
library(patchwork)
library(UCell)
library(qs2)
source(here("Brain-Met_V2/functions.R"))
# source(here("External_data/Fastq_processing/metadata_functions.R"))
```
# Setting paths and names

```{r}
exc_path <- here("Glioma_Project/01_data/Excel")
rmd_path <- here("Glioma_Project/02_knits/figs")
obj_path <- here("Glioma_Project/01_data")
fig_path <- here("Glioma_Project/04_figs")

object_name <- "Harmony"
reduction_name <- "Inhouse_Myeloid"
Processed_name <- "Myeloid"
sample_col <- "sample_name"
batch_cols <- c(
    "tumour_full", "tumour_abbreviated", "grade", "Cell_Type", "Cell_Subtype", "sample_name", "IDH_status",
    "FACS_sorting", "tier_correct", "cell_het_paper_id", "storage_condition", "prior_treatment", "gender", "Tumour_Margin",
    "Primary_or_Recurrent", "Previous_Surgery", "Radiotherapy", "Chemotherapy", "MGMT_Methylation"
)
continous_cols <- c("nCount_RNA", "nFeature_RNA", "percent.mt", "age_at_surgery_correct", "nuclear_fraction")


# subsetting <- c("Cell_Type", c("Myeloid", "Dendritic cells", "Mast cells")) #  Subset-col, cells_of_interest
subsetting <- c("Ann_lvl_1", c("Microglia", "Macrophage", "Myeloid_Prolif", "Mast-cells", "pDCs")) #  Subset-col, cells_of_interest

norm_meth_scale <- c(TRUE, "LogNormalize", 10000) # Perform log normalisatin, method, scale
vf <- c("vst", 2000, FALSE, FALSE) # VF method, amount, use old vf method, silence VDJgenes using scRep
scaling <- TRUE #
var.to.regress <- NULL # supply the var to be regressed if valid
harmony <- F # Run harmony or not
n_PCS <- 50 # Amount of Pcs to include
clustering <- c(TRUE, 4) # Perform clustering, Algorithm
sub_dir <- NULL
feature_vec_chosen <- feature_vec_overall
```


```{r read}
seurat_obj_path <- ifelse(length(sub_dir) > 0, here(obj_path, sub_dir, paste0(object_name, ".qs2")), here(obj_path, paste0(object_name, ".qs2")))
seurat_obj <- qs_read(seurat_obj_path)
.size(seurat_obj)
```

```{r processing seurat, eval = T, message = F, include = T}
seurat_obj <- .processing(
    obj = seurat_obj,
    reduction_name = reduction_name,
    Processed_name = Processed_name,
    subsetting = subsetting,
    norm_meth_scale = norm_meth_scale,
    vf = vf,
    scaling = scaling,
    var.to.regress = var.to.regress,
    harmony = harmony,
    n_PCS = n_PCS,
    clustering = clustering
)
```





```{r session}
sessionInfo()
```