
---
title: "Processing seurat object"
author: "Ivo Borkus"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
    toc_float: yes
    number_sections: yes
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = T, message = FALSE, warning = FALSE,
    fig.align = "center", fig.width = 10, fig.height = 10
)
knitr::render_markdown()
```

```{css, echo = F}
pre code, pre, code {
  white-space: pre !important;
  overflow-x: scroll !important;
  word-break: keep-all !important;
  word-wrap: initial !important;
}

pre {
  max-height: 300px;
  overflow-y: auto;
}
```


```{r loading libraries, include = FALSE}
library(Seurat)
library(dplyr)
library(ggplot2)
library(here)
library(tidyr)
library(patchwork)
library(qs2)
source(here("Brain-Met_V2/functions.R"))
# source(here("External_data/Fastq_processing/metadata_functions.R"))
```
# Setting paths and names

```{r}
# sub_dir <- "external"
exc_path <- here("Glioma_Project/01_data/Excel")
rmd_path <- here("Glioma_Project/02_knits/figs")
obj_path <- here("Glioma_Project/01_data")
fig_path <- here("Glioma_Project/04_Figs")



object_name <- "cnag_DG_immune.rds"
reduction_umap <- "umap"
reduction_pca <- "pca"
n_PCS <- 50

batch_cols <- c(
    "tumour_full", "tumour_abbreviated", "grade", "Cell_Type", "Cell_Subtype", "sample_name", "IDH_status",
    "FACS_sorting", "tier_correct", "cell_het_paper_id", "storage_condition", "prior_treatment", "gender", "Tumour_Margin",
    "Primary_or_Recurrent", "Previous_Surgery", "Radiotherapy", "Chemotherapy", "MGMT_Methylation"
)
continous_col <- c("nCount_RNA", "nFeature_RNA", "percent.mt")
```



```{r plotting some things}
feature_vec_overall <- c(
    "PTPRC", "CD3E", "CD3D", "CD4", "CD8A", "CD8B", "TOP2A", "MKI67", # T and prolif
    "CD1C", "HLA-DQB1", # DC
    "S100AB", "TREM2", "LGALS3", # Monocyte macrophage
    "TMEM119", # Microglial
    "MOG" # Oligos
)
feature_vec_T <- c("PTPRC", "CD8B", "CD4", "LAG3", "CX3CR1", "CCR7", "SELL", "NCAM1", "NKG7", "KLRB1", "FOXP3", "TOP2A", "MKI67", "PDCD1", "FCGR3A", "MAG")

feature_vec_chosen <- feature_vec_overall
```

```{r read}
seurat_obj <- readRDS(here(obj_path, object_name))
for (list_col in colnames(seurat_obj@meta.data)[lapply(seurat_obj@meta.data, class) == "list"]) {
    list_vec <- seurat_obj@meta.data[[list_col]]
    list_vec <- sapply(list_vec, function(x) if (length(x) == 0) NA else x)
    seurat_obj@meta.data[[paste0(list_col, "_correct")]] <- unlist(list_vec)
    print(paste0(list_col, "_correct"))
}
```

```{r}
seurat_obj@meta.data %>% colnames()
PCA_elbow <- ElbowPlot(seurat_obj, reduction = reduction_pca, ndims = n_PCS)

# Determine percent of variation associated with each PC
pct <- seurat_obj[[reduction_pca]]@stdev / sum(seurat_obj[[reduction_pca]]@stdev) * 100

# Calculate cumulative percents for each PC
cumu <- cumsum(pct)

# Determine which PC exhibits cumulative percent greater than 90% and % variation associated with the PC as less than 5
co1 <- which(cumu > 90 & pct < 5)[1]

co2 <- sort(which((pct[1:length(pct) - 1] - pct[2:length(pct)]) > 0.1), decreasing = T)[1] + 1

pcs <- min(co1, co2)
plot_df <- data.frame(
    pct = pct,
    cumu = cumu,
    rank = 1:length(pct)
)

# Elbow plot to visualize
ggplot(plot_df, aes(cumu, pct, label = rank, color = rank > pcs)) +
    geom_text() +
    geom_vline(xintercept = 90, color = "grey") +
    geom_hline(yintercept = min(pct[pct > 5]), color = "grey") +
    theme_bw()
```

```{r check pca regress}
matrix <- as.matrix(Embeddings(seurat_obj, reduction = reduction_pca)[, 1:n_PCS])

results <- list()
for (feature in c(batch_cols, continous_col)) {
    print(feature)
    print(class(seurat_obj@meta.data[[feature]]))
    temp_res <- sapply(colnames(matrix), function(pc) {
        model <- lm(matrix[, pc] ~ seurat_obj@meta.data[[feature]])
        summary(model)$r.squared
    })
    results[[feature]] <- temp_res
}
results <- as.data.frame(results)
results$PCs <- paste0("PC_", 1:n_PCS)

results$PCs <- factor(
    results$PCs,
    levels = paste0("PC_", 1:n_PCS)
)
df_corr <- as.data.frame(results) %>% tidyr::pivot_longer(cols = -c("PCs"), names_to = "QC", values_to = "cor")
```

```{r}
plot_list_batch <- plotting_PCA_regress(df_corr, limit_n = 1)
```

```{r plotting, results = 'asis', echo = F}
.tabsetter(plot_list_batch, overall_name = "Batch correction plots", path = rmd_path)
```

## Plotting confounders
```{r confounders, include = T, echo = T, eval = T, fig.width = 10, fig.height = 10}
seurat_obj@meta.data$percent_mt <- seurat_obj@meta.data$percent.mt

confounders <- c("nCount_RNA", "nFeature_RNA", "percent_mt")
plot <- .feature_plot(seurat_obj, reduction = reduction_umap, features = confounders, ncol = 2) & NoAxes()
plot
```

```{r creating batch_col plots}
metadata_list <- list()
for (batch_column in batch_cols) {
    print(batch_column)
    metadata_list[[batch_column]] <- .seurat_dimplot(seurat_obj, reduction = reduction_umap, group = batch_column)
}


for (col in continous_col) {
    print(col)
    class(seurat_obj@meta.data[[col]]) %>% print()
    seurat_obj@meta.data[[col]] <- as.numeric(seurat_obj@meta.data[[col]])
    is.na(seurat_obj@meta.data[[col]]) %>%
        table() %>%
        print()
}
```

```{r plotting some stuff, results = 'asis', echo = F}
# .tabsetter(metadata_list[[1]], overall_name = "Processing plots", path = rmd_path)
.tabsetter(metadata_list, overall_name = "Metadata plots", path = rmd_path)
```

## Sample name
```{r, fig.width = 20, fig.height = 10}
plot(metadata_list[["sample_name"]])
```



```{r plotting features}
size_vec <- length(feature_vec_chosen)
a <- 0
n <- 6
plot_list <- list()
for (i in seq(from = 1, to = size_vec, by = n)) {
    a <- a + 1
    if ((i + (n - 1)) > size_vec) {
        plot <- FeaturePlot(seurat_obj, reduction = reduction_umap, features = feature_vec_chosen[i:size_vec]) & NoLegend() & NoAxes()
    } else {
        plot <- FeaturePlot(seurat_obj, reduction = reduction_umap, features = feature_vec_chosen[i:(i + (n - 1))]) & NoLegend() & NoAxes()
    }

    plot_list[[paste0("Features: ", i, "-", (i + (n - 1)))]] <- plot
}
```


```{r plotting some stuff part 2, results = 'asis', echo = F}
# .tabsetter(metadata_list[[1]], overall_name = "Processing plots", path = rmd_path)
.tabsetter(plot_list, overall_name = "Feature plots", path = rmd_path)
```





```{r sessioninfo}
sessionInfo()
```


rmarkdown::render(
    input = here("Glioma_Project/Scripting/01_checking_file.rmd"),
    output_format = "html_document",
    output_dir = here("Glioma_Project/02_knits"),
    output_file = paste0(Sys.Date(),"_Checking_file.html")
)