
---
title: "Processing seurat object"
author: "Ivo Borkus"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
    toc_float: yes
    number_sections: yes
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = T, message = FALSE, warning = FALSE,
    fig.align = "center", fig.width = 10, fig.height = 10
)
# knitr::render_markdown()
```

```{css, echo = F}
pre code, pre, code {
  white-space: pre !important;
  overflow-x: scroll !important;
  word-break: keep-all !important;
  word-wrap: initial !important;
}

pre {
  max-height: 300px;
  overflow-y: auto;
}
```


```{r loading libraries, include = FALSE}
library(Seurat)
library(dplyr)
library(ggplot2)
library(here)
library(tidyr)
library(patchwork)
library(UCell)
library(qs2)
source(here("Brain-Met_V2/functions.R"))
# source(here("External_data/Fastq_processing/metadata_functions.R"))
```

# Setting paths and names

Here we set the variables necessary to run my custom scripts. The rest of the script therefore should not be tweaked. 

However, as there is an interpretation stage, all code after Results is custom for each object.
```{r}
exc_path <- here("Glioma_Project/01_data/Excel")
rmd_path <- here("Glioma_Project/02_knits/figs")
obj_path <- here("Glioma_Project/01_data")
fig_path <- here("Glioma_Project/04_figs")

object_name <- "Myeloid_Harmony_1000"
reduction_name <- "mg_mf_1000"
Processed_name <- "mg_mf_1000"
sample_col <- "sample_name"
batch_cols <- c(
    "tumour_full", "tumour_abbreviated", "grade", "Cell_Type", "Cell_Subtype", "sample_name", "IDH_status",
    "FACS_sorting", "tier_correct", "cell_het_paper_id", "storage_condition", "prior_treatment", "gender", "Tumour_Margin",
    "Primary_or_Recurrent", "Previous_Surgery", "Radiotherapy", "Chemotherapy", "MGMT_Methylation"
)
continous_cols <- c("nCount_RNA", "nFeature_RNA", "percent.mt", "age_at_surgery_correct", "nuclear_fraction")


# subsetting <- c("Cell_Type", c("Myeloid", "Dendritic cells", "Mast cells")) #  Subset-col, cells_of_interest
subsetting <- c("Ann_lvl_2M", c("Mg_inflam", "Mf_Inflam", "Mono_Classic", "mg_Anti_inflam", "BAMs", "Mg_classic", "BAMs_2", "Mf_IFN", "Mg_active", "Mg_PLCG2", "Mg_PLCG2+_2", "PLcG2_Bad_qual")) #  Subset-col, cells_of_interest
# new.cluster.ids <- c(
#     "Mg_inflam", "Mf_Inflam", "Myeloid_Prolif", "Mono_Classic", "DCs_CD1C+", "Myeloid_Prolif_2",
#     "Mg_PLCG2+_2", "Mt_high", "Hb_high", "pDCs", "Mast-cells", "mg_Anti_inflam", "BAMs", "Mg_classic", "BAMs_2", "Mf_IFN", "Mg_active", "PLCG2_Bad_qual", "Mg_PLCG2"
# )
norm_meth_scale <- c(F, "LogNormalize", 10000) # Perform log normalisatin, method, scale
vf <- c("vst", 1000, FALSE, FALSE) # VF method, amount, use old vf method, silence VDJgenes using scRep
scaling <- TRUE #
var.to.regress <- NULL # supply the var to be regressed if valid
harmony <- T # Run harmony or not
n_PCS <- 50 # Amount of Pcs to include
clustering <- c(TRUE, 4) # Perform clustering, Algorithm
sub_dir <- NULL
feature_vec_chosen <- feature_vec_overall
```


## Read in the object that is to be processed
```{r read}
seurat_obj_path <- ifelse(length(sub_dir) > 0, here(obj_path, sub_dir, paste0(object_name, ".qs2")), here(obj_path, paste0(object_name, ".qs2")))
seurat_obj <- qs_read(seurat_obj_path)
.size(seurat_obj)
seurat_obj$Ann_lvl_2M %>% unique()
```

# Processing object

```{r processing seurat, eval = T, message = F, include = T}
# Requires a joined seurat object of v5. Code bellow can be used to do this
# seurat_obj <- UpdateSeuratObject(seurat_obj)
# seurat_obj <- scCustomize::Convert_Assay(seurat_object = seurat_obj, convert_to = "V5")
# seurat_obj <- JoinLayers(seurat_obj)
seurat_obj <- .processing(
    obj = seurat_obj,
    reduction_name = reduction_name,
    Processed_name = Processed_name,
    subsetting = subsetting,
    norm_meth_scale = norm_meth_scale,
    vf = vf,
    scaling = scaling,
    var.to.regress = var.to.regress,
    harmony = harmony,
    n_PCS = n_PCS,
    clustering = clustering
)
```

```{R loading seurat}
# Loading it again, for easy working in the documented
seurat_obj_path <- ifelse(length(sub_dir) > 0, here(obj_path, sub_dir, paste0(Processed_name, ".qs2")), here(obj_path, paste0(Processed_name, ".qs2")))
seurat_obj <- qs_read(seurat_obj_path)
.size(seurat_obj)
```

```{r, eval = harmony, echo = harmony}
reduction_pca <- paste0("harmony_pca.", reduction_name)
reduction_umap <- paste0("umap.harmony.", reduction_name)
emb <- seurat_obj[[reduction_pca]]@cell.embeddings # 212005 × 200
variance <- apply(emb, 2, var)
pct <- variance / sum(variance) * 100
```

# results


```{r}
resolution_columns <- grep("^RNA_snn_res\\.",
    colnames(seurat_obj@meta.data),
    value = TRUE
)
resolution <- "RNA_snn_res.0.7"
.seurat_dimplot(seurat_obj, reduction = reduction_umap, group = "Sample", label = TRUE) & NoLegend()
.seurat_dimplot(seurat_obj, reduction = reduction_umap, group = resolution_columns, label = TRUE) & NoLegend()
.seurat_dimplot(seurat_obj, reduction = reduction_umap, group = "Ann_lvl_1", label = TRUE) & NoLegend()
plot_3 <- .seurat_dimplot(seurat_obj, reduction = reduction_umap, group = "Ann_lvl_2M", label = TRUE) & NoLegend()

plot <- FeaturePlot(seurat_obj, features = c("TMEM119", "LGALS3", "P2RY12", "SLC12A5", "TREM2", "APOE", "PLCG2", "ICAM1"), reduction = reduction_umap) & NoAxes()
plot_2 <- DimPlot(seurat_obj, reduction = reduction_umap, group.by = resolution, label = T) & NoLegend() & NoAxes()
plot + plot_2
ggsave(here(fig_path, "clusters_Myeloid.png"))
plot_3
ggsave(here(fig_path, "new_annos.png"))
```


```{r plotting signatures}
gene_list <- list(
    BD = c("LYZ", "EREG", "S100A8", "S100A9", "ITGAL", "ITGA4", "PTPRC", "FCGR3A", "CEBPD", "EGR2", "IRF4", "RUNX1", "STAT3", "CCL22", "CXCL2", "CD14", "S100A4", "S100A6", "FCN1", "VCAN", "CD36", "LGALS3", "MRC1", "CD163", "SELENOP", "SLC40A1", "CXCR4"),
    MG = c("P2RY12", "CX3CR1", "CSF1R", "AXL", "TMEM119", "CD84", "CSF3R", "ELMO1", "MEF2A", "BIN1", "SCIN", "FCGBP", "OLFML3", "NAV3", "SALL1", "SIGLEC8", "SLC1A3", "ITGAM", "TREM2", "PROS1", "SPARC", "PLCL1", "VIM", "APOE", "SMAD3", "P2RX7", "LYVE1", "MS4A7", "MRC1", "FOLR2", "CD163", "HLA-DRA", "TIMD4", "ADGRG1", "TGFBI", "CD74"),
    Mast = c("IL1RL1", "HDC", "TNFSF10", "FGL2", "IL17RB", "CCL2", "CSF1", "IL13"),
    pDCs = c("GZMB", "IGJ", "SERPINF1", "ITM2C", "IRF7", "TCF4", "BCL11A", "LILRA4", "MZB1", "DERL3", "IL3RA", "ZFAT", "NRP1", "CLEC4C", "IRF8", "SLC15A4", "BLNK"),
    DC_general = c("CD1C", "CLEC9A"),
    Prolif = c("UBE2C", "MKI67", "TOP2A"),
    Mg_homeostatic = c("PTPRC", "ITGAM", "P2RY12"),
    Mg_activated = c("CX3CR1", "GPR34", "FOXP2"),
    Mg_Reslike = c("PLCL1", "CEBPD", "VIM"),
    Mg_stress = c("HSPA1A", "HSPA1B", "SORCS2"),
    Mg_Phag = c("GPNMB", "RGCC", "PPARG"),
    Mg_Inflam = c("CCL4", "IL1B", "CCL3"),
    Mg_Inflam_ICAM1 = c("ICAM1", "RELB", "TNFAIP3"),
    Mg_INFg = c("IFNG", "IFIT2", "IFIT3", "STAT1"),
    BAM = c("F13A1", "LYVE1", "CD36"),
    BMD_Anti_Inflam = c("CD163", "SELENOP", "MRC1")
)
```

```{r,eval = T}
seurat_obj <- AddModuleScore_UCell(seurat_obj,
    features = gene_list
)

qs_save(seurat_obj, seurat_obj_path)
```



```{r, eval = T}
resolution_columns <- grep("^RNA_snn_res\\.",
    colnames(seurat_obj@meta.data),
    value = TRUE
)
.seurat_dimplot(seurat_obj, reduction = reduction_umap, group = resolution_columns, label = TRUE) & NoLegend()
.seurat_dimplot(seurat_obj, reduction = reduction_umap, group = "Ann_lvl_1", label = TRUE) & NoLegend()
FeaturePlot(seurat_obj, features = paste0(names(gene_list), "_UCell")[1:8], reduction = reduction_umap) & NoAxes()
FeaturePlot(seurat_obj, features = paste0(names(gene_list), "_UCell")[9:16], reduction = reduction_umap) & NoAxes()
```


```{r}
sessionInfo()
```